## Question 1

In [1]:
import pandas as pd
import numpy as np

In [66]:
pd.__version__

'1.4.4'

In [2]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-13 14:19:22--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1,4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1,36M  5,31KB/s    in 3m 45s  

2023-09-13 14:23:19 (6,17 KB/s) - ‘housing.csv’ saved [1423529/1423529]



In [3]:
df = pd.read_csv("./housing.csv")
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

## Question 2

In [5]:
df.shape[1]

10

## Question 3

In [6]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

## Question 4

In [8]:
df["ocean_proximity"].value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

In [11]:
len(df["ocean_proximity"].unique())

5

## Question 5

In [19]:
data = df[df["ocean_proximity"] == "NEAR BAY"]

In [22]:
data["ocean_proximity"].value_counts()

NEAR BAY    2290
Name: ocean_proximity, dtype: int64

In [24]:
round(data["median_house_value"].mean())

259212

## Question 6

In [28]:
mean_value = df["total_bedrooms"].mean()
print(mean_value)

537.8705525375618


In [32]:
df["total_bedrooms"] = df["total_bedrooms"].fillna(mean_value)

In [33]:
df["total_bedrooms"].isnull().sum()

0

In [34]:
df["total_bedrooms"].mean()

537.8705525375639

## Question 7

In [37]:
df[df["ocean_proximity"] == "ISLAND"]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [42]:
df_island = df[df["ocean_proximity"] == "ISLAND"]

In [46]:
df_island[["housing_median_age", "total_rooms", "total_bedrooms"]]

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [51]:
X = df_island[["housing_median_age", "total_rooms", "total_bedrooms"]].to_numpy()

In [52]:
print(X)

[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]


In [55]:
XT = X.T
print(XT)

[[  27.   52.   52.   52.   29.]
 [1675. 2359. 2127.  996.  716.]
 [ 521.  591.  512.  264.  214.]]


In [56]:
X.T.dot(X)

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [57]:
XTX = XT.dot(X)
print(XTX)

[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]


In [58]:
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]


In [61]:
y = np.array([950, 1300, 800, 1000, 1300])
#print(y)

In [65]:
w = XTX_inv.dot(XT).dot(y)
#print(w)

In [63]:
XTX_inv.dot(XT).dot(y)

array([23.12330961, -1.48124183,  5.69922946])